### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by ducc** [Sponges/DubTrack4J#1]
Comment here with things that should be changed/added

~~this means that it has been completed~~

**Comment by AkHo1ic** [comment]
I think you should have all ur urls stored in an enum

**Comment by Sponges** [comment]
Stop using Jsoup
Add layers of abstraction
Clean up code
Add support for events & features

**Comment by AkHo1ic** [comment]
Code blocks  https://github.com/Sponges/DubTrack4J/blob/master/src/main/java/pw/sponges/dubtrack4j/framework/event/EventManager.java#L26-L30

**Comment by Sponges** [comment]
Event system:
[01:38:02] @Kyle | pls: redesign it to allow easier implantation of custom methods
[01:38:18] @Kyle | pls: Cuz atm you cannot use anything but the 4 events

**Comment by Sponges** [comment]
Use GSON

**Comment by NotGGhost** [comment]
https://github.com/Sponges/DubTrack4J/blob/master/src/main/java/pw/sponges/dubtrack4j/Dubtrack.java#L144-L150

Downvote and upvote groups and/or song instances

**Comment by ducc** [comment]
~~Use Lombok~~
Not using a 3rd party library that affects the way my code compiles for an API.

**Comment by NotGGhost** [comment]
kys

**Comment by ducc** [comment]
Use code interceptors for cookies instead of if manually inserting the cookies each request

**Comment by ducc** [comment]
Use java logging & allow people to set their own logger

**Comment by csh** [comment]
> Use Lombok

Thank god you said no.

For logging you could use slf4j and provide the JDK binding OOB. It might also be nice if you use an implementation of the annotations from [JSR305](https://jcp.org/en/jsr/detail?id=305) to help static analysis tools that cannot automatically determine whether a method returns null or not.

**Comment by ducc** [comment]
@Fireflies mm might use slf4j idk, it seems pretty heavy for a lib

**Comment by ducc** [comment]
~~EventHandler is not thread safe.~~

Use TreeMap instead of Map for rooms

**Comment by csh** [comment]
> @Fireflies mm might use slf4j idk, it seems pretty heavy for a lib

~~Set it as a `runtime` dependency in maven so that it's not shaded.~~ By default slf4j will fall back to a NOP implementation if a compatible logging bundle can't be found on the classpath, a lot of popular libraries use a similar system.

Edit: You should probably use a maven profile to include it in your classpath for when testing, still won't be shaded.

**Comment by ducc** [comment]
Redesign user storage map in RoomImpl

**Comment by faminee** [comment]
List of apis used? I can't seem to find pubnub ;-;

**Comment by itsGhost** [comment]
[-] Java

**Comment by ducc** [comment]
@MrWhiteGoat https://github.com/Sponges/DubTrack4J/blob/master/pom.xml#L13-L37

```
org.json:json 20141113
com.pubnub:pubnub 3.7.5
commons-io:commons-io 2.4
com.squareup.okhttp3:okhttp 3.0.1
com.google.guava:guava 19.0
```

These should all be added when you include via maven. If not, you can find all of these dependencies and their jar files on mvnrepository.com

**Comment by itsGhost** [comment]
i swear to fuck give me another notification and i will hurt you

**Comment by csh** [comment]
ok

**Comment by itsGhost** [comment]
_pulls out a knife_
